 name: Download file X from Google Drive to default (./) directory
  uses: k0staa/download-gdrive-file-action@v1
  with:
    service-account-auth-json: ${{ secrets.SERVICE_ACCOUNT_AUTH_JSON }}
    download-file-name: bmw.jpg
